import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
      convocatorias:[
        {
          "idConvocatoria": 1,
          "nombreConvocatoria": "Resolución de 12 de noviembre del 2018, de la Dirección General de Telecomunicaciones y Sociedad de la Información, por la que se convoca en el año 2018 la concesión de subvenciones para Centros de Acceso Público a Internet al amparo de la Orden de 25 de enero del 2016",
          "yearConvocatoria": "2019",
          "idOrden": 0,
          "nombreOrden": "Orden de 25 de enero del 2016 que establece las bases reguladoras para la concesión de subvenciones destinadas a la dinamización de la Red de Acceso Público a Internet en Municipios, Entidades Locales Autónomas, Zonas de Transformación Social y Puntos de Acceso Público a Internet (BOJA 19 de 29/01/2016)",
          "aliasOrden": "25 de enero del 2016",
          "fechaInicio": "31-12-2018",
          "fechaFin": "29-12-2019",
          "importeAyuntamientoA": 9310,
          "importeAyuntamientoB": 14706,
          "importeAyuntamientoC": 7908,
          "importeELAA": 9310,
          "importeELAB": 14706,
          "fechaJustificacion": "04-05-2020",
          "importeGuadalinfoCorriente": 696124.5,
          "importeGuadalinfoFuturo": 232041.5,
          "importeELACorriente": 31977,
          "importeELAFuturo": 10659,
          "numeroDias": 365,
          "aplicacionPresupuestariaCorriente": "1500020000G/72A/76000/14012017000220",
          "aplicacionPresupuestariaFutura": "1500020000G/72A/76000/14012017000220",
          "resuelvePago": "décimo",
          "resuelveJustificacion": "décimo primero",
          "subag": "373/2018",
          "subco": "593/2018"
        },
        {
          "idConvocatoria": 79,
          "nombreConvocatoria": "Resolución de 24 de octubre del 2017, de la Dirección General de Telecomunicaciones y Sociedad de la Información, por la que se convoca para el año 2018 la concesión de subvenciones para Centros de Acceso Público a Internet al amparo de la Orden de 25 de enero del 2016",
          "yearConvocatoria": "2018",
          "idOrden": 0,
          "nombreOrden": "Orden de 25 de enero del 2016 que establece las bases reguladoras para la concesión de subvenciones destinadas a la dinamización de la Red de Acceso Público a Internet en Municipios, Entidades Locales Autónomas, Zonas de Transformación Social y Puntos de Acceso Público a Internet (BOJA 19 de 29/01/2016)",
          "aliasOrden": "25 de enero del 2016",
          "fechaInicio": "01-01-2018",
          "fechaFin": "31-12-2018",
          "importeAyuntamientoA": 9310,
          "importeAyuntamientoB": 14706,
          "importeAyuntamientoC": 7908,
          "importeELAA": 9310,
          "importeELAB": 14706,
          "fechaJustificacion": "02-05-2019",
          "importeGuadalinfoCorriente": 722170.5,
          "importeGuadalinfoFuturo": 240723.5,
          "importeELACorriente": 0,
          "importeELAFuturo": 0,
          "numeroDias": 365,
          "aplicacionPresupuestariaCorriente": "1500020000G/72A/76000/14012017000220",
          "aplicacionPresupuestariaFutura": "1500020000G/72A/76000/14012017000220",
          "resuelvePago": "octavo",
          "resuelveJustificacion": "noveno",
          "subag": "468/2017",
          "subco": "422/2017"
        }
      ],
      entidades: [
        {
            "idEntidad": 1,
            "nombreEntidad": "Adamuz",
            "acreedorGIRO": "87145",
            "cif": "P1400100B",
            "direccion": "C/ de la Fuente, 1",
            "codigoPostal": "14430",
            "municipio": "Adamuz",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 2,
            "nombreEntidad": "Aguilar de la Frontera",
            "acreedorGIRO": null,
            "cif": "P1400200J",
            "direccion": "Pz. San José, 1",
            "codigoPostal": "14920",
            "municipio": "Aguilar",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "C",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 3,
            "nombreEntidad": "Alcaracejos",
            "acreedorGIRO": null,
            "cif": "P1400300H",
            "direccion": "Pz. Los Pedroches, 1",
            "codigoPostal": "14480",
            "municipio": "Alcaracejos",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 4,
            "nombreEntidad": "Algallarín",
            "acreedorGIRO": null,
            "cif": "P1400004F",
            "direccion": "Pz. de la Constitución, 2",
            "codigoPostal": "14439",
            "municipio": "Adamuz",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ELA",
            "grupoEntidad": "A",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 5,
            "nombreEntidad": "Almedinilla",
            "acreedorGIRO": null,
            "cif": "P1400400F",
            "direccion": "Pz. de la Constitución, 1",
            "codigoPostal": "14812",
            "municipio": "Almedinilla",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 6,
            "nombreEntidad": "Almodóvar del Río",
            "acreedorGIRO": null,
            "cif": "P1400500C",
            "direccion": "Pz. de la Constitución, 4",
            "codigoPostal": "14720",
            "municipio": "Almodóvar",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 7,
            "nombreEntidad": "Añora",
            "acreedorGIRO": null,
            "cif": "P1400600A",
            "direccion": "Pz. de la Iglesia, 1",
            "codigoPostal": "14450",
            "municipio": "Añora",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 8,
            "nombreEntidad": "Belalcázar",
            "acreedorGIRO": null,
            "cif": "P1400800G",
            "direccion": "Pz. de la Constitución, 11",
            "codigoPostal": "14280",
            "municipio": "Belalcázar",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 9,
            "nombreEntidad": "Belmez",
            "acreedorGIRO": null,
            "cif": "P1400900E",
            "direccion": "C/ Córdoba, 1",
            "codigoPostal": "14240",
            "municipio": "Belmez",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 10,
            "nombreEntidad": "Benamejí",
            "acreedorGIRO": null,
            "cif": "P1401000C",
            "direccion": "Pz. de la Constitución, s/n",
            "codigoPostal": "14910",
            "municipio": "Benamejí",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 11,
            "nombreEntidad": "Los Blázquez",
            "acreedorGIRO": null,
            "cif": "P1401100A",
            "direccion": "Pz. de la Constitución, 1",
            "codigoPostal": "14208",
            "municipio": "Los Blázquez",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "A",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 12,
            "nombreEntidad": "Bujalance",
            "acreedorGIRO": null,
            "cif": "P14001200I",
            "direccion": "Pz. Mayor, 1",
            "codigoPostal": "14650",
            "municipio": "Bujalance",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 13,
            "nombreEntidad": "Cañete de las Torres",
            "acreedorGIRO": null,
            "cif": "P1401400E",
            "direccion": "Pz. de España, 1",
            "codigoPostal": "14660",
            "municipio": "Cañete",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 14,
            "nombreEntidad": "Carcabuey",
            "acreedorGIRO": null,
            "cif": "P1401500B",
            "direccion": "Pz. de España, 1",
            "codigoPostal": "14810",
            "municipio": "Carcabuey",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 15,
            "nombreEntidad": "Cardeña",
            "acreedorGIRO": null,
            "cif": "P1401600J",
            "direccion": "Paseo de Andalucía, 2",
            "codigoPostal": "14445",
            "municipio": "Cardeña",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 16,
            "nombreEntidad": "La Carlota",
            "acreedorGIRO": null,
            "cif": "P1401700H",
            "direccion": "Avda. Carlos III, 50",
            "codigoPostal": "14100",
            "municipio": "La Carlota",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "C",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 17,
            "nombreEntidad": "El Carpio",
            "acreedorGIRO": null,
            "cif": "P1401800F",
            "direccion": "Pz. de la Constitución, 1",
            "codigoPostal": "14620",
            "municipio": "El Carpio",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 18,
            "nombreEntidad": "Castil de Campos",
            "acreedorGIRO": null,
            "cif": "P1400029C",
            "direccion": "Pz. Nueva, 1",
            "codigoPostal": "14815",
            "municipio": "Priego",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ELA",
            "grupoEntidad": "A",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 19,
            "nombreEntidad": "Castro del Río",
            "acreedorGIRO": null,
            "cif": "P1401900D",
            "direccion": "Pz. San Fernando, 1",
            "codigoPostal": "14840",
            "municipio": "Castro del Río",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 20,
            "nombreEntidad": "Conquista",
            "acreedorGIRO": null,
            "cif": "P1402000B",
            "direccion": "C/ Mayor, 16",
            "codigoPostal": "14480",
            "municipio": "Conquista",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "A",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 21,
            "nombreEntidad": "Doña Mencía",
            "acreedorGIRO": null,
            "cif": "P1402200H",
            "direccion": "Pz. Andalucía, 1",
            "codigoPostal": "14860",
            "municipio": "Doña Mencía",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 22,
            "nombreEntidad": "Dos Torres",
            "acreedorGIRO": null,
            "cif": "P1402300F",
            "direccion": "Pz. de la Villa, 1",
            "codigoPostal": "14460",
            "municipio": "Dos Torres",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 23,
            "nombreEntidad": "Encinarejo",
            "acreedorGIRO": null,
            "cif": "P1400005C",
            "direccion": "Pz. de Andalucía, s/n",
            "codigoPostal": "14711",
            "municipio": "Córdoba",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ELA",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 24,
            "nombreEntidad": "Encinas Reales",
            "acreedorGIRO": null,
            "cif": "P1402400D",
            "direccion": "Pz. de la Democracia",
            "codigoPostal": "14913",
            "municipio": "Encinas Reales",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 25,
            "nombreEntidad": "Espejo",
            "acreedorGIRO": null,
            "cif": "P1402500A",
            "direccion": "Pz. de la Constitución, 5",
            "codigoPostal": "14830",
            "municipio": "Espejo",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 26,
            "nombreEntidad": "Espiel",
            "acreedorGIRO": null,
            "cif": "P1402600I",
            "direccion": "C/ Andalucía, 7",
            "codigoPostal": "14220",
            "municipio": "Espiel",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 27,
            "nombreEntidad": "Fernán Núñez",
            "acreedorGIRO": null,
            "cif": "P1402700G",
            "direccion": "Pz. de Armas, 5",
            "codigoPostal": "14520",
            "municipio": "Fernán Núñez",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 28,
            "nombreEntidad": "Fuente Carreteros",
            "acreedorGIRO": null,
            "cif": "P1400007I",
            "direccion": "C/ Espada, 2",
            "codigoPostal": "14110",
            "municipio": "Fuente Carreteros",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 29,
            "nombreEntidad": "Fuente la Lancha",
            "acreedorGIRO": null,
            "cif": "P1402800E",
            "direccion": "Pz. Sotomayor y Zúñiga, 1",
            "codigoPostal": "14260",
            "municipio": "Fuente la Lancha",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "A",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 30,
            "nombreEntidad": "Fuente Obejuna",
            "acreedorGIRO": null,
            "cif": "P1402900C",
            "direccion": "Pz. Lope de Vega, 1",
            "codigoPostal": "14290",
            "municipio": "Fuente Obejuna",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 31,
            "nombreEntidad": "Fuente Palmera",
            "acreedorGIRO": null,
            "cif": "P1403000A",
            "direccion": "Pz. Real, 1",
            "codigoPostal": "14120",
            "municipio": "Fuente Palmera",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 32,
            "nombreEntidad": "Fuente Tójar",
            "acreedorGIRO": null,
            "cif": "P1403100I",
            "direccion": "C/ Castil de Campos, 4",
            "codigoPostal": "14815",
            "municipio": "Fuente Tójar",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "A",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 33,
            "nombreEntidad": "La Granjuela",
            "acreedorGIRO": null,
            "cif": "P1403200G",
            "direccion": "C/ María Amaro, 1",
            "codigoPostal": "14207",
            "municipio": "La Granjuela",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "A",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 34,
            "nombreEntidad": "Guadalcázar",
            "acreedorGIRO": null,
            "cif": "P1403300E",
            "direccion": "C/ María Auxiliadora, 4",
            "codigoPostal": "14130",
            "municipio": "Guadalcázar",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 35,
            "nombreEntidad": "La Guijarrosa",
            "acreedorGIRO": null,
            "cif": "P1400041H",
            "direccion": "Avda. Molino Blanco, 3",
            "codigoPostal": "14547",
            "municipio": "La Guijarrosa",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 36,
            "nombreEntidad": "El Guijo",
            "acreedorGIRO": null,
            "cif": "P1403400C",
            "direccion": "Pz. de la Constitución, 3",
            "codigoPostal": "14413",
            "municipio": "El Guijo",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "A",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 37,
            "nombreEntidad": "Hinojosa del Duque",
            "acreedorGIRO": null,
            "cif": "P1403500J",
            "direccion": "Pz de la Catedral, 1",
            "codigoPostal": "14270",
            "municipio": "Hinojosa ",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 38,
            "nombreEntidad": "Hornachuelos",
            "acreedorGIRO": null,
            "cif": "P1403600H",
            "direccion": "Pz. de la Constitución, 1",
            "codigoPostal": "14740",
            "municipio": "Hornachuelos",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 39,
            "nombreEntidad": "Iznajar",
            "acreedorGIRO": null,
            "cif": "P1403700F",
            "direccion": "C/Julio Burell, 17",
            "codigoPostal": "14970",
            "municipio": "Iznajar",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 40,
            "nombreEntidad": "Luque",
            "acreedorGIRO": null,
            "cif": "P1403900B",
            "direccion": "Pz de España, 11",
            "codigoPostal": "14880",
            "municipio": "Luque",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 41,
            "nombreEntidad": "Montalbán",
            "acreedorGIRO": null,
            "cif": "P1404000J",
            "direccion": "Pz Andalucía, 10",
            "codigoPostal": "14548",
            "municipio": "Montalbán",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 42,
            "nombreEntidad": "Montemayor",
            "acreedorGIRO": null,
            "cif": "P1404100H",
            "direccion": "Pz. de la Constitución, 1",
            "codigoPostal": "14530",
            "municipio": "Montemayor",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 43,
            "nombreEntidad": "Montoro",
            "acreedorGIRO": null,
            "cif": "P1404300D",
            "direccion": "Pz de España, 1",
            "codigoPostal": "14600",
            "municipio": "Montoro",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 44,
            "nombreEntidad": "Monturque",
            "acreedorGIRO": null,
            "cif": "P1404400B",
            "direccion": "Pz. de la Constitución, 3",
            "codigoPostal": "14930",
            "municipio": "Monturque",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 45,
            "nombreEntidad": "Moriles",
            "acreedorGIRO": null,
            "cif": "P1404500I",
            "direccion": "Avda. de Andalucía, 23",
            "codigoPostal": "14510",
            "municipio": "Moriles",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 46,
            "nombreEntidad": "Nueva Carteya",
            "acreedorGIRO": null,
            "cif": "P1404600G",
            "direccion": "Pz. Marques de Estella, 9",
            "codigoPostal": "14857",
            "municipio": "Nueva Carteya",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 47,
            "nombreEntidad": "Obejo",
            "acreedorGIRO": null,
            "cif": "P1404700E",
            "direccion": "C/ Iglesia, 16",
            "codigoPostal": "14310",
            "municipio": "Obejo",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 48,
            "nombreEntidad": "Ochavillo del Río",
            "acreedorGIRO": null,
            "cif": "P1400048C",
            "direccion": "C/ Escuelas, 8",
            "codigoPostal": "14129",
            "municipio": "Ochavillo del Río (Fuente Palmera)",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ELA",
            "grupoEntidad": "A",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 49,
            "nombreEntidad": "Palenciana",
            "acreedorGIRO": null,
            "cif": "P1404800C",
            "direccion": "C/ San Isidro, 22",
            "codigoPostal": "14914",
            "municipio": "Palenciana",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 50,
            "nombreEntidad": "Pedro Abad",
            "acreedorGIRO": null,
            "cif": "P1405000I",
            "direccion": "C/Espino, 75",
            "codigoPostal": "14630",
            "municipio": "Pedro Abad",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 51,
            "nombreEntidad": "Pedroche",
            "acreedorGIRO": null,
            "cif": "P1405100G",
            "direccion": "Pz. de las Siete Villas, 1",
            "codigoPostal": "14412",
            "municipio": "Pedroche",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 52,
            "nombreEntidad": "Peñarroya- Pueblonuevo",
            "acreedorGIRO": null,
            "cif": "P14052000E",
            "direccion": "C/ Constitución, 5",
            "codigoPostal": "14200",
            "municipio": "Peñarroya-Pueblonuevo",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "C",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 53,
            "nombreEntidad": "Posadas",
            "acreedorGIRO": null,
            "cif": "P1405300C",
            "direccion": "Pz. del Ayuntamiento, s/n",
            "codigoPostal": "14730",
            "municipio": "Posadas",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 54,
            "nombreEntidad": "La Rambla",
            "acreedorGIRO": null,
            "cif": "P1405700D",
            "direccion": "Pz. de la Constitución, 7",
            "codigoPostal": "14540",
            "municipio": "La Rambla",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 55,
            "nombreEntidad": "Rute",
            "acreedorGIRO": null,
            "cif": "P1405800B",
            "direccion": "C/ Toledo, 2",
            "codigoPostal": "14960",
            "municipio": "Rute",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 56,
            "nombreEntidad": "San Sebastián de los Ballesteros",
            "acreedorGIRO": null,
            "cif": "P1405900J",
            "direccion": "Pz. del Fuero, 1",
            "codigoPostal": "14150",
            "municipio": "San Sebastián de los Ballesteros",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "A",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 57,
            "nombreEntidad": "Santa Eufemia",
            "acreedorGIRO": null,
            "cif": "P1406100F",
            "direccion": "Pz. Mayor, 1",
            "codigoPostal": "14491",
            "municipio": "Santa Eufemia",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "A",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 58,
            "nombreEntidad": "Santaella",
            "acreedorGIRO": null,
            "cif": "P1406000H",
            "direccion": "Pz. Mayor, 6",
            "codigoPostal": "14546",
            "municipio": "Santaella",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 59,
            "nombreEntidad": "Torrecampo",
            "acreedorGIRO": null,
            "cif": "P1406200D",
            "direccion": "Pz. de Jesús, 19",
            "codigoPostal": "14410",
            "municipio": "Torrecampo",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 60,
            "nombreEntidad": "Valenzuela",
            "acreedorGIRO": null,
            "cif": "P14006300B",
            "direccion": "Pz de España, 2",
            "codigoPostal": "14670",
            "municipio": "Valenzuela",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 61,
            "nombreEntidad": "Valsequillo",
            "acreedorGIRO": null,
            "cif": "P1406400J",
            "direccion": "Pz. de la Constitución, 1",
            "codigoPostal": "14206",
            "municipio": "Valsequillo",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "A",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 62,
            "nombreEntidad": "La Victoria",
            "acreedorGIRO": null,
            "cif": "P1406500G",
            "direccion": "Pz de España, 7",
            "codigoPostal": "14140",
            "municipio": "La Victoria",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 63,
            "nombreEntidad": "Villa del Río",
            "acreedorGIRO": null,
            "cif": "P1406600E",
            "direccion": "Pz. de la Constitución, 8",
            "codigoPostal": "14640",
            "municipio": "Villa del Río",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 64,
            "nombreEntidad": "Villafranca de Córdoba",
            "acreedorGIRO": null,
            "cif": "P1406700C",
            "direccion": "C/ Alcolea, 24",
            "codigoPostal": "14420",
            "municipio": "Villafranca de Córdoba",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 65,
            "nombreEntidad": "Villaharta",
            "acreedorGIRO": null,
            "cif": "P1406800A",
            "direccion": "C/ Virgen de la Piedad, 1",
            "codigoPostal": "14210",
            "municipio": "Villaharta",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "A",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 66,
            "nombreEntidad": "Villanueva de Córdoba",
            "acreedorGIRO": null,
            "cif": "P1406900I",
            "direccion": "Pz de España, 10",
            "codigoPostal": "14440",
            "municipio": "Villanueva de Córdoba",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 67,
            "nombreEntidad": "Villanueva del Duque",
            "acreedorGIRO": null,
            "cif": "P1407000G",
            "direccion": "Pz. Duque de Béjar, 1",
            "codigoPostal": "14250",
            "municipio": "Villanueva del Duque",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 68,
            "nombreEntidad": "Villanueva del Rey",
            "acreedorGIRO": null,
            "cif": "P1407100E",
            "direccion": "C/ Real, 6",
            "codigoPostal": "14230",
            "municipio": "Villanueva del Rey",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 69,
            "nombreEntidad": "Villaralto",
            "acreedorGIRO": null,
            "cif": "P1407200C",
            "direccion": "C/ Del Ayuntamiento s/n",
            "codigoPostal": "14490",
            "municipio": "Villaralto",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 70,
            "nombreEntidad": "Villaviciosa de Córdoba",
            "acreedorGIRO": null,
            "cif": "P14073000A",
            "direccion": "Pz Andalucía, 1",
            "codigoPostal": "14430",
            "municipio": "Villaviciosa de Córdoba",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 71,
            "nombreEntidad": "El Viso",
            "acreedorGIRO": null,
            "cif": "P1407400I",
            "direccion": "Pz. de la Constitución, 1",
            "codigoPostal": "14470",
            "municipio": "El Viso",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "B",
            "posicionIBAN": null,
            "iban": null
        },
        {
            "idEntidad": 72,
            "nombreEntidad": "Zuheros",
            "acreedorGIRO": null,
            "cif": "P1407500F",
            "direccion": "C/ Horno, 50",
            "codigoPostal": "14870",
            "municipio": "Zuheros",
            "provincia": "Córdoba",
            "emailAyuntamiento": null,
            "emailCentro": null,
            "tipoEntidad": "ayuntamiento",
            "grupoEntidad": "A",
            "posicionIBAN": null,
            "iban": null
        }
    ],
      ordenes: [
      {
        "idOrden": 0,
        "nombreOrden": "Orden de 25 de enero del 2016 que establece las bases reguladoras para la concesión de subvenciones destinadas a la dinamización de la Red de Acceso Público a Internet en Municipios, Entidades Locales Autónomas, Zonas de Transformación Social y Puntos de Acceso Público a Internet (BOJA 19 de 29/01/2016)",
        "aliasOrden": "25 de enero del 2016"
      }
    ],
      idConvocatoriaTrabajo: 1
    
  },
  getters: {
    getConvocatorias: (state)=>state.convocatorias,
    getOrdenes: (state)=> state.ordenes,
    getEntidades: (state)=>state.entidades,
    getIdConvocatoriaTrabajo: (state)=>state.idConvocatoriaTrabajo

  },
  mutations: {
    cambiarConvocatoriaTrabajo: (state,payload) => state.idConvocatoriaTrabajo = payload
    
    
  },
  actions: {
    cambiarConvocatoriaTrabajoAsync: (context,payload) => context.commit('cambiarConvocatoriaTrabajo',payload)
  }
})
